#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $MINETESTDIR = "/home/mtowner/MultiCraft2";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $startpath = $ENV{'PATH'};
my $newpath = "$MINETESTDIR/exec:$startpath";
my $exists = "";

# Set ENV vars
$ENV{'PATH'} = $newpath;
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep multicraftserver|grep -v grep`;

# check if Multicraft process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $MINETESTDIR;
	# check if Multicraft process is running
	$running=`ps ax|grep multicraftserver|grep -v grep`;
	if ($running eq "")
	{
		print "Multicraft not running\n";
		# See if they want the server started
		if (! -f "$MINETESTDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Multicraft Down, Restarting: $datestring";
			open(OUTF, ">>$MINETESTDIR/MulticraftScreen.log") || die "Unable to open $MINETESTDIR/MulticraftScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $MINETESTDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S Multicraft -d -U -m $MINETESTDIR/bin/multicraftserver");
		}
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
